name: Install Boost on Windows

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest
    steps:
        - name: Download boost binary
          run: Invoke-WebRequest "https://boostorg.jfrog.io/artifactory/main/release/1.83.0/binaries/boost_1_83_0-msvc-14.3-64.exe" -OutFile "C:\temp\boost.exe"
        - name: Install boost binary
          run: Start-Process -Wait -FilePath "C:\temp\boost.exe" -ArgumentList "/S" -PassThru
        - name: List boost content
          run: ls -r C:\local
