name: Install Boost on Windows

# on:
#   workflow_dispatch:
on:
  push:
     branches: [ main ]

env:
  BOOST_VERSION: 1.83.0
  BOOST_INSTALL_DIR: C:\local
  QUANTLIB_VERSION: 1.31.1


jobs:
  build:
    runs-on: windows-2022
    steps:
        - name: Install Boost
          uses: MarkusJx/install-boost@v2.4.4
          id: install-boost
          with:
            boost_version: ${{ env.BOOST_VERSION }}
            # OPTIONAL: Specify a custon install location
            boost_install_dir: ${{ env.BOOST_INSTALL_DIR }}
            # OPTIONAL: Specify a platform version
            platform_version: 2022
            # OPTIONAL: Specify a toolset
            toolset: msvc
        - name: Checkout QuantLib
          uses: actions/checkout@v4
          with:
            repository: lballabio/QuantLib
            ref: v${{ env.QUANTLIB_VERSION }}
            path: QuantLib
        - name: Enable thread save observer pattern in QL source code
          run: |
           $filePath = '.\QuantLib\ql\userconfig.hpp'
           $tempFilePath = "$env:TEMP\$($filePath | Split-Path -Leaf)"
           $find = "//#    define QL_ENABLE_THREAD_SAFE_OBSERVER_PATTERN"
           $replace = "#    define QL_ENABLE_THREAD_SAFE_OBSERVER_PATTERN"
           (Get-Content -Path $filePath) -replace $find, $replace | Add-Content -Path $tempFilePath
           Move-Item -Path $tempFilePath -Destination $filePath -Force
        - name: Edit vcxproj to include Boost dependency for msbuild
          run: |
           $filePath = '.\QuantLib\QuantLib.vcxproj'
           $tempFilePath = "$env:TEMP\$($filePath | Split-Path -Leaf)"
           $find = @'
           <PropertyGroup Label="UserMacros" />
           '@
           $replace = @'
           <PropertyGroup Label="UserMacros" />
           <PropertyGroup>
             <IncludePath>${{ env.BOOST_INSTALL_DIR }}\boost\boost;$(VC_IncludePath);$(WindowsSDK_IncludePath);</IncludePath>
             <LibraryPath>${{ env.BOOST_INSTALL_DIR }}\boost\boost\lib;$(VC_LibraryPath_x64);$(WindowsSDK_LibraryPath_x64)</LibraryPath>
           </PropertyGroup>
           '@
           (Get-Content -Path $filePath) -replace $find, $replace | Add-Content -Path $tempFilePath
           Move-Item -Path $tempFilePath -Destination $filePath -Force
           Get-Content -Path $filePath